### ISSUE TITLE
Website should be served through TLS

### ISSUE THREAD

**Issue by graingert** [PyconUK/2016.pyconuk.org#215]
GitLab supports TLS out of the box. They do not support SSL.

https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/

As an added bonus it will let you build using django-amber without having to push to branches etc.

**Comment by graingert** [comment]
This won't be changing the DNS nameservers as suggested in https://github.com/PyconUK/2016.pyconuk.org/issues/105

It would just be updating the CNAMEs (and pushing the built static files to GitLab, or moving the project to GitLab and using their build tools)

**Comment by graingert** [comment]
![](https://3.bp.blogspot.com/-DG70U0Y-y9w/V9Cwuym53AI/AAAAAAAAAW0/6zO81T_hqWMjdAF_YYK7dfXV-26DL7OYACLcB/s1600/blog%2Bimage%2B2.png)

**Comment by inglesp** [comment]
Thanks @graingert -- this is something for next year.

**Comment by graingert** [comment]
@inglesp I've created https://gitlab.com/PyconUK/ in case you want to use it. Who should I transfer it to?

**Comment by inglesp** [comment]
Thanks @graingert.  Could you transfer it to @ghickman?

**Comment by graingert** [comment]
@inglesp transferred

**Comment by inglesp** [comment]
👍

**Comment by graingert** [comment]
@inglesp  @ghickman I've dropped myself down to 'Developer' feel free to kickban me if you want

**Comment by ghickman** [comment]
@graingert – thanks for this.  Sounds like you're volunteering to help out with infra/ops for next year ;)

I'm also keen to host the site via TLS, however I agree with Peter it's a job for next year.  We did look into it for this year but of course were limited by GitHub Pages.  It would be ideal for us to stay on GitHub if they roll out TLS for Pages sites between now and next year (which I believe is coming) since we already have all the conf's code here and permission configured.

**Comment by ghickman** [comment]
Now that GitHub Pages supports this I've enabled it for this deployment.
